PROJECT='PROJECT'
BUCKET='BUCKET'
INPUT_NAME=''
NETWORK='vpc-NETWORK'
SUBNETWORK='SUBNETWORK'
SERVICE_ACCOUNT_FILE = 'SERVICE_ACCOUNT_FILE'
SERVICE_ACCOUNT_PATH = '/tmp'


# [File detail]
file_path = 'file_path'
file_name = 'final_doc_list.txt'

# [PROD DB]
HOST='HOST'
USER='USER'
PASSWORD='PASSWORD'
DBNAME='DBNAME'
PORT=PORT
